# Generated by Django 5.1.15 on 2026-03-23 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('spotify_url', models.URLField(blank=True, default='', max_length=500)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('instagram_url', models.URLField(blank=True, default='', max_length=500)),
                ('website_url', models.URLField(blank=True, default='', max_length=500)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('profile_score', models.IntegerField(default=0)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='jobs.job')),
            ],
            options={
                'db_table': 'groovon_artist',
                'ordering': ['-profile_score', 'name'],
            },
        ),
    ]
