# Generated by Django 5.1.15 on 2026-03-23 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('excel', 'Excel Upload'), ('api', 'API Search'), ('artist_list', 'Artist List')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('running', '🔄 Running'), ('completed', '✅ Completed'), ('failed', '❌ Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_phase', models.CharField(blank=True, default='', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('total_events', models.IntegerField(default=0)),
                ('total_artists', models.IntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('output_json', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groovon_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
